name: Push Test Workflow

on:
  push:
    branches:
      - rutest   # change this to the branch you want to test
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "✅ Push event detected on branch $GITHUB_REF"
